/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.sun.awt.AWTUtilities;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.Timer;

/**
 *
 * @author IVÁN UTRIA
 */
public class Ppal extends javax.swing.JDialog {

    int width = (Toolkit.getDefaultToolkit().getScreenSize().width) - 300;
    public Ppal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        AWTUtilities.setWindowOpaque(this, false);
        this.setLocation(width,20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSegundos = new javax.swing.JLabel();
        lblAMmPm = new javax.swing.JLabel();
        lblMinutos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblSegundos1 = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSegundos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSegundos.setForeground(new java.awt.Color(255, 255, 255));
        lblSegundos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSegundos.setText("00");
        getContentPane().add(lblSegundos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 70, 40));

        lblAMmPm.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblAMmPm.setForeground(new java.awt.Color(102, 102, 102));
        lblAMmPm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAMmPm.setText("--");
        getContentPane().add(lblAMmPm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 110, 70));

        lblMinutos.setFont(new java.awt.Font("Dialog", 1, 200)); // NOI18N
        lblMinutos.setForeground(new java.awt.Color(255, 255, 255));
        lblMinutos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinutos.setText("00");
        getContentPane().add(lblMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 240, 170));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        lblSegundos1.setBackground(new java.awt.Color(0, 0, 0));
        lblSegundos1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblSegundos1.setForeground(new java.awt.Color(0, 0, 0));
        lblSegundos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSegundos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/path815.png"))); // NOI18N
        getContentPane().add(lblSegundos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 70, 80));

        lblHora.setFont(new java.awt.Font("Dialog", 1, 200)); // NOI18N
        lblHora.setForeground(new java.awt.Color(204, 51, 0));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setText("00");
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 240, 170));

        setSize(new java.awt.Dimension(288, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        timer = new Timer(1000, new Crometro());
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    public class Crometro implements ActionListener{
        public void actionPerformed(ActionEvent evt){
            GregorianCalendar tiempo = new GregorianCalendar();
            String h,m,s,ampm;
            h = tiempo.get(Calendar.HOUR)>9 ? ""+tiempo.get(Calendar.HOUR) : "0"+tiempo.get(Calendar.HOUR);
            h = h.equals("00") ? String.valueOf(12) : h;
            m = tiempo.get(Calendar.MINUTE)>9 ? ""+tiempo.get(Calendar.MINUTE):"0"+tiempo.get(Calendar.MINUTE);
            s = tiempo.get(Calendar.SECOND)>9 ? ""+tiempo.get(Calendar.SECOND) : "0"+tiempo.get(Calendar.SECOND);
            ampm = tiempo.get(Calendar.AM_PM) == Calendar.AM ? "A.M" : "P.M";
            lblHora.setText(h);
            lblMinutos.setText(m);
            lblSegundos.setText(s);
            lblAMmPm.setText(ampm);
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ppal dialog = new Ppal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private Timer timer;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAMmPm;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblMinutos;
    private javax.swing.JLabel lblSegundos;
    private javax.swing.JLabel lblSegundos1;
    // End of variables declaration//GEN-END:variables
}
